scene.setBackgroundImage(assets.image`background`)
let _1 = sprites.create(assets.image`1`, SpriteKind.Player)
let _2 = sprites.create(assets.image`2`, SpriteKind.Player)
let _3 = sprites.create(assets.image`3`, SpriteKind.Player)
let _4 = sprites.create(assets.image`4`, SpriteKind.Player)
let _5 = sprites.create(assets.image`5`, SpriteKind.Player)
_1.setPosition(68, 76)
_2.setPosition(109, 60)
_3.setPosition(42, 67)
_4.setPosition(26, 44)
_5.setPosition(134, 43)
